steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fakeapp-gcp/fakenewshacklytics','.']
    timeout: 6000s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fakeapp-gcp/fakenewshacklytics']
    timeout: 6000s
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint:  gcloud
    args: ['run','deploy','fakeapp-service','--image','gcr.io/fakeapp-gcp/fakenewshacklytics','--region','us-central1','--platform','managed']
timeout: 6000s

images:
  - gcr.io/fakeapp-gcp/fakenewshacklytics